[package]
name = "revm-inspectors"
description = "Revm inspector implementations"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.0"
license = "MIT or Apache-2.0"
homepage = "https://github.com/paradigmxyz/evm-inspectors"
repository = "https://github.com/paradigmxyz/evm-inspectors"
categories = ["cryptography"]
keywords = ["ethereum", "evm", "inspectors", "tracing", "debugging"]

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rustdoc.all = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"

[dependencies]
# eth
alloy-sol-types = "0.6"
alloy-primitives = "0.6"
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-trace-types = { git = "https://github.com/alloy-rs/alloy" }

# revm = "4.0"
revm = { git = "https://github.com/bluealloy/revm", branch = "main", default-features = false, features = [
    "std",
] }

# js-tracing-inspector
boa_engine = { version = "0.17", optional = true }
boa_gc = { version = "0.17", optional = true }

serde = { version = "1", features = ["derive"] }
thiserror = { version = "1", optional = true }
serde_json = { version = "1", optional = true }

[features]
default = []
js-tracer = ["boa_engine", "boa_gc", "thiserror", "serde_json"]
